// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess.Migrations
{
    [DbContext(typeof(ChessDbContext))]
    [Migration("20260320002540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("GameHistory", b =>
                {
                    b.Property<int>("GameHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameHistoryId");

                    b.ToTable("GameHistories");
                });

            modelBuilder.Entity("GameHistoryPlayer", b =>
                {
                    b.Property<int>("GameHistoriesGameHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamePlayersPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameHistoriesGameHistoryId", "GamePlayersPlayerId");

                    b.HasIndex("GamePlayersPlayerId");

                    b.ToTable("GameHistoryPlayer");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameHistoryPlayer", b =>
                {
                    b.HasOne("GameHistory", null)
                        .WithMany()
                        .HasForeignKey("GameHistoriesGameHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player", null)
                        .WithMany()
                        .HasForeignKey("GamePlayersPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
